const actionTypes = {
    ADD_INGREDIENT: 'ADD_INGREDIENT',
    REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
    SET_INGREDIENTS_FROM_SERVER: 'SET_INGREDIENTS_FROM_SERVER',
    SET_SERVER_ERROR: 'SET_SERVER_ERROR',

    INIT_PURCHASE: 'INIT_PURCHASE',
    START_PURCHASING_BURGER: 'START_PURCHASING_BURGER',
    SUCCESS_PURCHASING_BURGER: 'SUCCESS_PURCHASING_BURGER',
    FAIL_PURCHASING_BURGER: 'FAIL_PURCHASING_BURGER',

    FETCH_ORDERS_START: 'FETCH_ORDERS_START',
    SET_ORDERS: 'SET_ORDERS',
    FETCH_ORDERS_FAIL: 'FETCH_ORDERS_FAIL',

    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',
    LOG_OUT: 'LOG_OUT',
    SET_REDIRECT_PATH: 'SET_REDIRECT_PATH'
}

export default actionTypes;